openapi: "3.0.0"
info:
  title: Tshirt short API
  description: LCO - a course to create API for ecomm store
  version: 1.1.0
  contact:
    email: kapilshakyawal5@gmail.com
    url: "https://lco.in"

# servers:
#   - url: "https://localhost:/api/v1"
#     description: for local host - secure
#   - url: "http://localhost:/api/v1"
#     description: for local host - regular

servers:
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for local host - secure
    variables:
      version:
        enum:
          - v1
          - v2
        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /dummy:
    get:
      tags:
        - Home:
      summary: returns a greet message from LCO
      responses:
        200:
          description: All good success
          content:
            application/json:
              schema:
                type: object
                example: "mystring"
        400:
          description: All bad request
        500:
          description: All internal server error